import type { Product } from "@/data/products";
import type { ProductDetailFaq, ProductDetailImage, ProductDetailJourneyStep } from "@/lib/products/detail";

export type ProductDetailCategory =
  | "abalone"
  | "eel"
  | "fish"
  | "shellfish"
  | "shrimp"
  | "meal-kit"
  | "gift"
  | "default";

export type AutoGeneratedGalleryItem = ProductDetailImage & {
  role: string;
  badge: string;
  title: string;
  caption: string;
};

export type AutoGeneratedReview = {
  score: string;
  title: string;
  body: string;
  metric: string;
};

export type AutoGeneratedDetailModel = {
  category: ProductDetailCategory;
  brandStory: string;
  productionStory: string;
  freshnessStory: string;
  purchasePoint: string;
  finalCta: string;
  comparison: {
    normal: string;
    pado: string;
  };
  benefits: string[];
  purchaseReasons: string[];
  packaging: string[];
  timeline: ProductDetailJourneyStep[];
  gallery: AutoGeneratedGalleryItem[];
  faq: ProductDetailFaq[];
  reviews: AutoGeneratedReview[];
  seo: {
    title: string;
    description: string;
    ogTitle: string;
    ogDescription: string;
    keywords: string[];
  };
};

type CategoryProfile = {
  label: string;
  storyNoun: string;
  freshnessNoun: string;
  productionFocus: string;
  packagingFocus: string;
  eatingFocus: string;
  benefits: string[];
  faq: ProductDetailFaq[];
  reviewTitles: string[];
};

const CATEGORY_PROFILES: Record<ProductDetailCategory, CategoryProfile> = {
  abalone: {
    label: "활전복",
    storyNoun: "살아있는 신선함",
    freshnessNoun: "활도",
    productionFocus: "크기와 활도를 확인해 선별",
    packagingFocus: "산소포장과 냉장 포장",
    eatingFocus: "전복버터구이, 전복죽, 전복찜",
    benefits: ["완도 산지 기준 선별", "활도 확인 후 포장", "산소포장으로 신선도 유지", "크기별 옵션 선택", "선물용으로도 좋은 구성"],
    faq: [
      { question: "전복은 살아서 도착하나요?", answer: "상품 상태와 배송 환경에 따라 차이가 있지만 활도 유지를 기준으로 선별·포장합니다." },
      { question: "어떻게 보관하나요?", answer: "수령 후 가능한 빨리 드시고, 바로 드시지 않을 경우 냉장 보관 후 안내에 따라 손질해 주세요." },
      { question: "오후 1시 이후 주문은 언제 출고되나요?", answer: "평일 오후 1시 이후 주문은 다음 영업일 출고를 기준으로 안내합니다." }
    ],
    reviewTitles: ["활도가 좋아 안심됐어요", "선물로 보내기 좋았어요"]
  },
  eel: {
    label: "바다장어",
    storyNoun: "손질의 편리함",
    freshnessNoun: "손질 상태",
    productionFocus: "구이용으로 먹기 좋게 손질",
    packagingFocus: "냉장 포장과 누수 방지",
    eatingFocus: "장어구이, 덮밥, 보양식",
    benefits: ["손질 완료로 조리 간편", "구이용으로 좋은 두께", "담백한 풍미", "빠른 출고", "가정식 보양 메뉴에 적합"],
    faq: [
      { question: "손질되어 오나요?", answer: "상품 옵션에 맞춰 조리하기 편한 형태로 준비합니다." },
      { question: "양념이 포함되나요?", answer: "옵션 구성에 따라 다르며, 포함 여부는 상품 구성품 영역에서 확인할 수 있습니다." },
      { question: "냉장인가요 냉동인가요?", answer: "상품별 출고 기준에 따라 냉장 또는 냉동 포장하며 상세 안내를 함께 표시합니다." }
    ],
    reviewTitles: ["굽기 편해서 좋았어요", "비린내가 적고 담백했어요"]
  },
  fish: {
    label: "생선",
    storyNoun: "한 끼의 완성도",
    freshnessNoun: "선도",
    productionFocus: "크기와 선도를 확인해 손질",
    packagingFocus: "냉장·냉동 신선 포장",
    eatingFocus: "구이, 조림, 찜",
    benefits: ["가정식에 좋은 구성", "손질 부담 감소", "선도 기준 확인", "조리하기 좋은 크기", "냉장 배송 기준 적용"],
    faq: [
      { question: "손질 상태는 어떻게 되나요?", answer: "상품 옵션과 출고 기준에 맞춰 손질 상태를 안내합니다." },
      { question: "구이용인가요 조림용인가요?", answer: "대부분 구이와 조림 모두 가능하며, 추천 조리법은 상세페이지에 표시합니다." },
      { question: "보관은 어떻게 하나요?", answer: "수령 후 빠르게 섭취하거나 냉장·냉동 기준에 맞춰 보관해 주세요." }
    ],
    reviewTitles: ["손질이 편했어요", "밥반찬으로 좋았어요"]
  },
  shellfish: {
    label: "조개류",
    storyNoun: "제철의 식감",
    freshnessNoun: "식감",
    productionFocus: "크기와 상태를 확인해 선별",
    packagingFocus: "냉장 신선 포장",
    eatingFocus: "숙회, 찜, 탕",
    benefits: ["제철 식감", "크기 선별", "산지 직송", "냉장 포장", "술안주와 식탁 메뉴에 적합"],
    faq: [
      { question: "해감이 필요한가요?", answer: "상품군에 따라 다르며, 수령 후 세척·해감 안내를 함께 확인해 주세요." },
      { question: "어떻게 먹으면 좋나요?", answer: "숙회, 찜, 탕 등 식감이 살아나는 조리법을 추천합니다." },
      { question: "수령 후 바로 먹어야 하나요?", answer: "신선식품 특성상 가능한 빠른 섭취를 권장합니다." }
    ],
    reviewTitles: ["식감이 좋았어요", "술안주로 만족했어요"]
  },
  shrimp: {
    label: "새우",
    storyNoun: "탱글한 식감",
    freshnessNoun: "탄력",
    productionFocus: "크기와 상태를 확인해 선별",
    packagingFocus: "냉장·냉동 포장",
    eatingFocus: "구이, 찜, 감바스",
    benefits: ["구이용으로 좋은 크기", "탱글한 식감", "손쉬운 조리", "가족 식사 추천", "빠른 출고"],
    faq: [
      { question: "새우 크기는 일정한가요?", answer: "옵션별 규격을 기준으로 선별하지만 자연산·수산물 특성상 약간의 편차가 있을 수 있습니다." },
      { question: "냉동 보관 가능한가요?", answer: "수령 후 바로 드시지 않을 경우 상품 안내에 맞춰 냉동 보관해 주세요." },
      { question: "어떤 요리에 어울리나요?", answer: "소금구이, 찜, 감바스, 파스타 등에 잘 어울립니다." }
    ],
    reviewTitles: ["탱글해서 맛있었어요", "아이들도 잘 먹었어요"]
  },
  "meal-kit": {
    label: "밀키트",
    storyNoun: "간편한 한 끼",
    freshnessNoun: "조리 편의성",
    productionFocus: "재료와 구성품을 조리 동선에 맞춰 준비",
    packagingFocus: "재료별 분리 포장",
    eatingFocus: "간편 조리, 아침 식사, 선물",
    benefits: ["간편 조리", "재료 준비 부담 감소", "일정한 맛", "보관 편의", "가정식 구성"],
    faq: [
      { question: "조리 시간이 얼마나 걸리나요?", answer: "상품별 차이가 있지만 간편 조리를 기준으로 구성합니다." },
      { question: "추가 재료가 필요한가요?", answer: "기본 구성 외 기호에 따라 채소나 양념을 더할 수 있습니다." },
      { question: "보관 방법은 어떻게 되나요?", answer: "수령 후 상품 안내에 맞춰 냉장 또는 냉동 보관해 주세요." }
    ],
    reviewTitles: ["간편해서 좋았어요", "아침 식사로 든든했어요"]
  },
  gift: {
    label: "선물세트",
    storyNoun: "받는 분의 만족감",
    freshnessNoun: "구성 완성도",
    productionFocus: "선물 목적에 맞춰 구성과 포장 상태를 확인",
    packagingFocus: "보냉 포장과 선물 포장",
    eatingFocus: "명절, 감사 인사, 가족 선물",
    benefits: ["선물용 구성", "보냉 포장", "받는 분을 고려한 가격대", "산지 상품 조합", "감사 인사에 적합"],
    faq: [
      { question: "선물 포장이 가능한가요?", answer: "상품 구성과 포장 옵션에 따라 선물용 포장 상태로 준비합니다." },
      { question: "받는 분 주소로 바로 보낼 수 있나요?", answer: "주문 시 배송지에 받는 분 정보를 입력하면 해당 주소로 발송할 수 있습니다." },
      { question: "구성 변경이 가능한가요?", answer: "현재 제공되는 옵션 기준으로 선택 가능하며, 별도 구성은 고객센터로 문의해 주세요." }
    ],
    reviewTitles: ["선물 받으신 분이 좋아했어요", "포장이 깔끔했어요"]
  },
  default: {
    label: "수산물",
    storyNoun: "산지의 신선함",
    freshnessNoun: "신선도",
    productionFocus: "상품 상태를 확인해 선별",
    packagingFocus: "상품 특성에 맞춘 신선 포장",
    eatingFocus: "가정식과 선물",
    benefits: ["산지 기준 선별", "빠른 출고", "신선 포장", "옵션별 선택", "믿고 주문하는 구성"],
    faq: [
      { question: "언제 출고되나요?", answer: "평일 오후 1시 이전 주문은 당일 출고를 기준으로 운영합니다." },
      { question: "상품 상태가 다르면 어떻게 하나요?", answer: "수령 즉시 사진과 함께 고객센터로 문의해 주시면 확인 후 안내합니다." },
      { question: "보관은 어떻게 하나요?", answer: "상품별 안내에 맞춰 냉장 또는 냉동 보관해 주세요." }
    ],
    reviewTitles: ["신선해서 만족했어요", "포장이 안정적이었어요"]
  }
};

export function buildAutoGeneratedDetail(product: Product): AutoGeneratedDetailModel {
  const category = inferProductDetailCategory(product);
  const profile = CATEGORY_PROFILES[category];
  const imageSource = collectImages(product);
  const gallery = imageSource.map((image, index) => buildGalleryItem(image, index, product, profile));
  const totalStock = product.options.reduce((sum, option) => sum + Number(option.stock ?? 0), 0);
  const shippingTitle = product.shippingInfo?.title || "평일 오후 1시 이전 주문 당일 출고";

  return {
    category,
    brandStory: `${product.origin}에서 준비한 ${product.name}은 ${profile.storyNoun}을 고객이 바로 이해할 수 있도록 사진, 옵션, 배송 기준을 한 흐름으로 보여줍니다.`,
    productionStory: `${profile.productionFocus}한 뒤 ${profile.packagingFocus} 기준으로 출고합니다. 고객은 상품을 받기 전부터 어떤 상태로 도착하는지 예측할 수 있습니다.`,
    freshnessStory: `${profile.freshnessNoun}을 지키기 위해 선별, 포장, 배송 안내를 분리하지 않고 하나의 구매 흐름 안에서 확인하게 설계했습니다.`,
    purchasePoint: `${shippingTitle}, ${product.origin} 기준 선별, ${totalStock > 0 ? `현재 구매 가능 재고 ${totalStock}개` : "현재 재입고 안내"}를 구매 전 바로 확인할 수 있습니다.`,
    finalCta: `${product.name}은 ${profile.eatingFocus}에 잘 어울립니다. 옵션과 수량을 확인한 뒤 신선한 상태로 받아보세요.`,
    comparison: {
      normal: "일반 상품 상세는 사진과 설명이 분리되어 실제 상태와 배송 기준을 한눈에 파악하기 어렵습니다.",
      pado: `파도스토리는 ${product.origin}, ${profile.productionFocus}, ${profile.packagingFocus}을 한 페이지에서 확인하도록 구성합니다.`
    },
    benefits: mergeUnique([...(product.highlights || []), ...profile.benefits]).slice(0, 6),
    purchaseReasons: buildPurchaseReasons(product, profile, totalStock),
    packaging: [
      profile.packagingFocus,
      product.shippingInfo?.title || "평일 오후 1시 이전 주문 당일 출고",
      "상품 특성에 맞춘 보냉 포장",
      "수령 후 보관 안내 제공"
    ],
    timeline: buildTimeline(product, profile, gallery),
    gallery,
    faq: mergeFaq(product.detail?.faq, profile.faq),
    reviews: buildReviews(product, profile),
    seo: buildAutoSeo(product, profile)
  };
}

export function inferProductDetailCategory(product: Product): ProductDetailCategory {
  const text = `${product.slug} ${product.name} ${product.category}`.toLowerCase();
  if (/gift|선물|세트/.test(text)) return "gift";
  if (/meal|kit|porridge|soup|죽|미역국|밀키트|간편/.test(text)) return "meal-kit";
  if (/abalone|전복/.test(text)) return "abalone";
  if (/eel|장어|아나고/.test(text)) return "eel";
  if (/shrimp|새우/.test(text)) return "shrimp";
  if (/conch|oyster|shell|굴|소라|조개/.test(text)) return "shellfish";
  if (/fish|galchi|godeungeo|hairtail|mackerel|갈치|고등어|홍어|생선/.test(text)) return "fish";
  return "default";
}

function collectImages(product: Product): ProductDetailImage[] {
  const detailImages = product.detail?.heroImages?.filter((image) => image.url) || [];
  const baseImages = detailImages.length
    ? detailImages
    : [{ label: "대표사진", url: product.image, description: product.subtitle }];
  const seen = new Set<string>();
  return baseImages
    .filter((image) => {
      if (!image.url || seen.has(image.url)) return false;
      seen.add(image.url);
      return true;
    })
    .slice(0, 20);
}

function buildGalleryItem(
  image: ProductDetailImage,
  index: number,
  product: Product,
  profile: CategoryProfile
): AutoGeneratedGalleryItem {
  const role = inferImageRole(image, index);
  const roleCopy: Record<string, { badge: string; title: string; caption: string }> = {
    main: { badge: "MAIN", title: `${product.name} 대표 이미지`, caption: `${product.origin} 기준으로 선별한 상품의 첫인상을 확인하세요.` },
    size: { badge: "SIZE", title: "크기와 구성 확인", caption: "받아볼 상품의 크기감과 구성 이해를 돕는 사진입니다." },
    freshness: { badge: "FRESH", title: `${profile.freshnessNoun} 확인`, caption: `${profile.freshnessNoun}과 질감을 사진으로 먼저 확인할 수 있습니다.` },
    component: { badge: "SET", title: "실제 구성품", caption: "고객이 받는 구성품을 한눈에 확인하도록 배치합니다." },
    packaging: { badge: "PACK", title: profile.packagingFocus, caption: "배송 중 신선도를 지키기 위한 포장 상태를 보여줍니다." },
    recipe: { badge: "TABLE", title: "맛있게 먹는 장면", caption: `${profile.eatingFocus}로 즐기기 좋은 상품입니다.` },
    shipping: { badge: "SHIP", title: "배송 준비", caption: "출고 전 포장과 배송 기준을 확인할 수 있습니다." },
    detail: { badge: "PHOTO", title: image.label || `상세 사진 ${index + 1}`, caption: image.description || "상품 상태를 더 자세히 확인할 수 있는 사진입니다." }
  };
  const copy = roleCopy[role] || roleCopy.detail;
  return {
    ...image,
    role,
    badge: copy.badge,
    title: copy.title,
    caption: image.description || copy.caption
  };
}

function inferImageRole(image: ProductDetailImage, index: number) {
  const text = `${image.label} ${image.description || ""} ${image.url}`.toLowerCase();
  if (index === 0 || /대표|main|hero/.test(text)) return "main";
  if (/크기|비교|size/.test(text)) return "size";
  if (/신선|질감|fresh|선도|활도/.test(text)) return "freshness";
  if (/구성|component|set/.test(text)) return "component";
  if (/포장|박스|package|pack|ice/.test(text)) return "packaging";
  if (/조리|식탁|recipe|table|cook/.test(text)) return "recipe";
  if (/배송|출고|ship|delivery/.test(text)) return "shipping";
  return "detail";
}

function buildPurchaseReasons(product: Product, profile: CategoryProfile, totalStock: number) {
  return [
    product.shippingInfo?.title || "평일 오후 1시 이전 주문 당일 출고",
    `${product.origin} 기준 산지 확인`,
    profile.packagingFocus,
    totalStock > 0 ? `현재 구매 가능 재고 ${totalStock}개` : "재입고 알림 준비",
    `${profile.eatingFocus}에 적합`,
    product.discountRate > 0 ? `${product.discountRate}% 할인 적용` : "정직한 판매가"
  ];
}

function buildTimeline(product: Product, profile: CategoryProfile, gallery: AutoGeneratedGalleryItem[]): ProductDetailJourneyStep[] {
  const existing = product.detail?.journey?.filter((step) => step.description || step.image) || [];
  if (existing.length) return existing;
  const imageFor = (role: string) => gallery.find((image) => image.role === role)?.url || gallery[0]?.url || product.image;
  return [
    { key: "origin", title: "산지", image: imageFor("main"), description: `${product.origin}에서 상품 기준에 맞는 물량을 확인합니다.` },
    { key: "sorting", title: "선별", image: imageFor("freshness"), description: profile.productionFocus },
    { key: "packing", title: "포장", image: imageFor("packaging"), description: profile.packagingFocus },
    { key: "delivery", title: "배송", image: imageFor("shipping"), description: product.shippingInfo?.title || "평일 오후 1시 이전 주문은 당일 출고합니다." },
    { key: "table", title: "식탁", image: imageFor("recipe"), description: `${profile.eatingFocus}로 맛있게 즐기기 좋습니다.` }
  ];
}

function mergeFaq(detailFaq: ProductDetailFaq[] | undefined, fallback: ProductDetailFaq[]) {
  const base = (detailFaq || []).filter((item) => item.question || item.answer);
  if (base.length >= 3) return base;
  const used = new Set(base.map((item) => item.question));
  return [...base, ...fallback.filter((item) => !used.has(item.question))].slice(0, 6);
}

function buildReviews(product: Product, profile: CategoryProfile): AutoGeneratedReview[] {
  return [
    {
      score: "4.9",
      title: profile.reviewTitles[0],
      body: `${product.origin} 상품이라는 점과 포장 상태를 함께 확인할 수 있어 구매 전 기대한 상태와 가까웠다는 반응을 준비합니다.`,
      metric: "신선도 만족"
    },
    {
      score: "BEST",
      title: profile.reviewTitles[1],
      body: `${profile.packagingFocus} 기준이 보여 선물이나 가족 식사용으로 선택하기 쉬웠다는 후기를 노출할 예정입니다.`,
      metric: "포장 만족"
    },
    {
      score: "98%",
      title: "배송 안내가 명확했어요",
      body: "출고 기준과 보관 안내가 상세페이지에 함께 있어 수령 후 처리 방법을 빠르게 확인할 수 있습니다.",
      metric: "배송 만족"
    }
  ];
}

function buildAutoSeo(product: Product, profile: CategoryProfile) {
  const title = `${product.name} | ${product.origin} 산지직송 ${profile.label}`;
  const description = `${product.name}을 ${product.origin} 기준으로 선별해 ${profile.packagingFocus}으로 발송합니다. ${profile.eatingFocus}에 어울리는 프리미엄 수산물 상세페이지입니다.`;
  return {
    title,
    description: description.length > 155 ? `${description.slice(0, 152).trim()}...` : description,
    ogTitle: `${product.name} - PADO STORY`,
    ogDescription: `${profile.storyNoun}, ${profile.packagingFocus}, 빠른 출고 기준을 한눈에 확인하세요.`,
    keywords: mergeUnique([product.name, product.origin, product.category, profile.label, "파도스토리", "산지직송", "수산물"]).slice(0, 10)
  };
}

function mergeUnique(items: string[]) {
  const seen = new Set<string>();
  return items
    .map((item) => String(item || "").trim())
    .filter((item) => {
      if (!item || seen.has(item)) return false;
      seen.add(item);
      return true;
    });
}
