import { NextResponse } from "next/server";
import { readJsonBody } from "@/lib/api/request";
import { hasInvalidProductOption, parseProductOptions } from "@/lib/admin/product-options";
import { requireAdminApi } from "@/lib/auth/admin-api";
import { normalizeProductDetailInput } from "@/lib/products/detail";
import { createProductSlug } from "@/lib/products/slug";
import { createAdminClient } from "@/lib/supabase/admin";

const isMissingOptionPriceColumn = (error: { code?: string; message: string } | null) =>
  Boolean(error && (error.code === "PGRST204" || (error.message.includes("schema cache") && error.message.includes("price"))));

async function writeProductOperationLogBestEffort(
  supabase: ReturnType<typeof createAdminClient>,
  input: {
    eventType: string;
    summary: string;
    productId: string;
    actorId: string;
    actorEmail?: string;
    payload?: Record<string, unknown>;
  }
) {
  await supabase
    .from("operation_logs")
    .insert({
      event_type: input.eventType,
      summary: input.summary,
      payload: {
        productId: input.productId,
        ...(input.payload ?? {})
      },
      actor: {
        id: input.actorId,
        email: input.actorEmail ?? null,
        type: "admin"
      }
    })
    .then(() => undefined, () => undefined);
}

export async function GET(request: Request) {
  const admin = await requireAdminApi();
  if (!admin.ok) return admin.response;

  const supabase = createAdminClient();
  const searchParams = new URL(request.url).searchParams;
  const slugQuery = searchParams.get("slug");
  if (slugQuery !== null) {
    const requestedSlug = createProductSlug({ slug: slugQuery });
    let query = supabase.from("products").select("id, slug").eq("slug", requestedSlug);
    const excludeId = searchParams.get("excludeId");
    if (excludeId) query = query.neq("id", excludeId);
    const { data, error } = await query.maybeSingle();
    if (error) return NextResponse.json({ ok: false, message: error.message }, { status: 500 });
    return NextResponse.json({ ok: true, slug: requestedSlug, available: !data });
  }
  const { data, error } = await supabase
    .from("products")
    .select("*, product_options(*)")
    .order("created_at", { ascending: false });

  if (error) return NextResponse.json({ ok: false, message: error.message }, { status: 500 });
  return NextResponse.json({ ok: true, products: data });
}

export async function POST(request: Request) {
  const admin = await requireAdminApi();
  if (!admin.ok) return admin.response;

  const parsedBody = await readJsonBody(request);
  if (!parsedBody.ok) return parsedBody.response;
  const body = parsedBody.body;
  if (body.productId || body.id) {
    return NextResponse.json(
      { ok: false, code: "CREATE_WITH_PRODUCT_ID", message: "신규 상품 등록 요청에는 기존 상품 ID를 포함할 수 없습니다." },
      { status: 400 }
    );
  }
  const supabase = createAdminClient();
  const actorId = admin.session.user.id;
  const actorEmail = admin.session.user.email;

  const requiredFields = ["name", "origin", "category", "subtitle", "description", "basePrice"] as const;
  const missingField = requiredFields.find((field) => !String(body[field] ?? "").trim());
  if (missingField) {
    return NextResponse.json({ ok: false, message: "필수 상품 정보를 모두 입력해주세요." }, { status: 400 });
  }

  let basePrice = Number(body.basePrice);
  if (!Number.isFinite(basePrice) || basePrice < 0) {
    return NextResponse.json({ ok: false, message: "기본 가격은 0원 이상의 숫자로 입력해주세요." }, { status: 400 });
  }

  const baseSlug = createProductSlug({ slug: body.slug, name: body.name, origin: body.origin });
  let slug = baseSlug;

  if (!slug) {
    return NextResponse.json({ ok: false, message: "영문 상품 URL(slug)을 만들 수 없습니다. 예: wando-live-abalone" }, { status: 400 });
  }

  const { data: duplicateProduct, error: duplicateError } = await supabase
    .from("products")
    .select("id, slug, name, is_active")
    .eq("slug", slug)
    .maybeSingle();

  if (duplicateError) {
    return NextResponse.json({ ok: false, message: duplicateError.message }, { status: 500 });
  }

  if (duplicateProduct) {
    if (body.slugAutoGenerated) {
      for (let suffix = 2; suffix <= 999; suffix += 1) {
        const candidate = `${baseSlug}-${suffix}`;
        const { data, error } = await supabase.from("products").select("id").eq("slug", candidate).maybeSingle();
        if (error) return NextResponse.json({ ok: false, message: error.message }, { status: 500 });
        if (!data) {
          slug = candidate;
          break;
        }
      }
    } else {
    return NextResponse.json(
      {
        ok: false,
        code: "DUPLICATE_SLUG",
        slug,
        message: `이미 같은 URL 이름(slug)의 상품이 있습니다: ${duplicateProduct.name} (${slug})`
      },
      { status: 409 }
    );
    }
  }

  const optionInputs = parseProductOptions(body.options, "기본 옵션", basePrice);

  if (!optionInputs.length || hasInvalidProductOption(optionInputs)) {
    return NextResponse.json(
      { ok: false, message: "옵션 형식을 확인해주세요. 예: 1kg|0|30" },
      { status: 400 }
    );
  }
  basePrice = Math.min(...optionInputs.map((option) => option.price));

  const isActive = body.isActive === undefined ? true : Boolean(body.isActive);
  const reservedNote =
    body.publishMode === "reserved" && body.reservedAt
      ? `예약 공개 예정: ${String(body.reservedAt)}`
      : "";

  const { data: product, error } = await supabase
    .from("products")
    .insert({
      slug,
      name: body.name,
      origin: body.origin,
      category: body.category,
      subtitle: body.subtitle,
      description: body.description,
      base_price: basePrice,
      image_url: body.imageUrl || "/images/product-placeholder.svg",
      badge: body.badge || null,
      detail_json: normalizeProductDetailInput(body.detailJson ?? body.detail_json),
      highlights: String(body.highlights ?? "")
        .split(",")
        .map((item) => item.trim())
        .filter(Boolean)
        .concat(reservedNote ? [reservedNote] : []),
      is_active: isActive
    })
    .select()
    .single();

  if (error) {
    const isDuplicate = error.code === "23505";
    const isMissingDetailColumn = error.message.includes("detail_json");
    return NextResponse.json(
      {
        ok: false,
        message: isDuplicate
          ? "이미 같은 URL 이름(slug)의 상품이 있습니다."
          : isMissingDetailColumn
            ? "Supabase products.detail_json 컬럼이 필요합니다. SQL Editor에서 alter table products add column if not exists detail_json jsonb not null default '{}'::jsonb; 를 먼저 실행해주세요."
            : error.message
      },
      { status: isDuplicate ? 409 : 500 }
    );
  }

  const options = optionInputs.map((option) => ({ ...option, product_id: product.id }));

  let { error: optionError } = await supabase.from("product_options").insert(options);
  if (isMissingOptionPriceColumn(optionError)) {
    const legacyOptions = options.map(({ price, ...option }) => ({ ...option, price_delta: price - basePrice }));
    ({ error: optionError } = await supabase.from("product_options").insert(legacyOptions));
  }
  if (optionError) {
    await supabase.from("products").update({ is_active: false }).eq("id", product.id);
    return NextResponse.json({ ok: false, message: optionError.message }, { status: 500 });
  }

  await writeProductOperationLogBestEffort(supabase, {
    eventType: "product.created",
    summary: "상품을 등록했습니다.",
    productId: product.id,
    actorId,
    actorEmail,
    payload: {
      slug: product.slug,
      isActive
    }
  });

  return NextResponse.json({
    ok: true,
    product,
    productId: product.id,
    productSlug: product.slug,
    productUrl: `/products/${product.slug}`,
    message: `상품 등록완료: ${product.name} (${product.slug})`
  });
}
