"use client";

import { useCallback, useEffect, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { formatPrice } from "@/data/products";
import { buildTrackingUrl } from "@/lib/shipping/tracking-url";
import { customerGradeLabels, type CustomerGrade, type CustomerStats } from "@/lib/customers/operations";
import { AdminToast } from "@/components/admin/ui";

type Customer = { id: string; name: string; phone: string; email: string; role: string; createdAt: string; lastLoginAt: string | null; status: string; tags: string[]; grade: CustomerGrade; stats: CustomerStats };
type Summary = { todayJoined: number; weekJoined: number; vip: number; caution: number; dormant: number; recentCs: number; todayCs: number };
type Detail = { customer: Customer & { created_at: string }; orders: Array<Record<string, unknown>>; addresses: Array<Record<string, unknown>>; logs: Array<Record<string, unknown>>; timeline: Array<Record<string, unknown>> };
type Pagination = { page: number; pageSize: number; total: number; pageCount: number };
const initialSummary: Summary = { todayJoined: 0, weekJoined: 0, vip: 0, caution: 0, dormant: 0, recentCs: 0, todayCs: 0 };

export function AdminCustomersManager() {
  const router = useRouter(); const searchParams = useSearchParams(); const paramsKey = searchParams.toString();
  const [customers, setCustomers] = useState<Customer[]>([]); const [pagination, setPagination] = useState<Pagination>({ page: 1, pageSize: 20, total: 0, pageCount: 1 }); const [summary, setSummary] = useState(initialSummary); const [query, setQuery] = useState(searchParams.get("q") ?? ""); const [selectedId, setSelectedId] = useState<string | null>(null); const [detail, setDetail] = useState<Detail | null>(null); const [message, setMessage] = useState("고객을 불러오는 중입니다.");
  const [loadState, setLoadState] = useState<"loading" | "ready" | "error">("loading");
  const value = (key: string, fallback = "all") => searchParams.get(key) ?? fallback;
  const updateParams = useCallback((updates: Record<string, string | null>) => { const next = new URLSearchParams(paramsKey); Object.entries(updates).forEach(([key, nextValue]) => nextValue && nextValue !== "all" ? next.set(key, nextValue) : next.delete(key)); if (!("page" in updates)) next.delete("page"); router.replace(`/admin/members${next.size ? `?${next}` : ""}`, { scroll: false }); }, [paramsKey, router]);
  const load = useCallback(async () => { setLoadState("loading"); try { const response = await fetch(`/api/admin/customers${paramsKey ? `?${paramsKey}` : ""}`, { cache: "no-store" }); const result = await response.json(); if (!response.ok) throw new Error(); setCustomers(result.customers ?? []); setPagination(result.pagination); setSummary(result.summary ?? initialSummary); setMessage(result.pagination.total ? `검색 조건에 맞는 고객 ${result.pagination.total}명입니다.` : "검색 조건에 맞는 고객이 없습니다."); setLoadState("ready"); } catch { setCustomers([]); setMessage("고객 정보를 불러오지 못했습니다. 잠시 후 다시 시도해 주세요."); setLoadState("error"); } }, [paramsKey]);
  const loadDetail = useCallback(async (id: string) => { setSelectedId(id); setDetail(null); const response = await fetch(`/api/admin/customers/${id}`, { cache: "no-store" }); const result = await response.json(); if (!response.ok) { setMessage(result.message); return; } setDetail(result); }, []);
  useEffect(() => { void load(); }, [load]); useEffect(() => { setQuery(searchParams.get("q") ?? ""); }, [paramsKey, searchParams]); useEffect(() => { const close = (event: KeyboardEvent) => { if (event.key === "Escape") { setSelectedId(null); setDetail(null); } }; window.addEventListener("keydown", close); return () => window.removeEventListener("keydown", close); }, []);
  const start = pagination.total ? (pagination.page - 1) * pagination.pageSize + 1 : 0; const end = Math.min(pagination.page * pagination.pageSize, pagination.total);
  return <>
    <form className="admin-customer-search" onSubmit={(event) => { event.preventDefault(); updateParams({ q: query.trim() || null }); }}><div><input value={query} onChange={(event) => setQuery(event.target.value)} aria-label="고객 통합 검색" placeholder="이름, 전화번호, 이메일, 회원 ID, 주문번호, 송장번호, 배송지, 태그" /><button className="button teal">검색</button><button type="button" onClick={() => { setQuery(""); router.replace("/admin/members", { scroll: false }); }}>초기화</button></div><div>
      <label>등급<select value={value("grade")} onChange={(event) => updateParams({ grade: event.target.value })}><option value="all">전체</option>{Object.entries(customerGradeLabels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label>
      <label>주문여부<select value={value("orders")} onChange={(event) => updateParams({ orders: event.target.value })}><option value="all">전체</option><option value="yes">주문 있음</option><option value="no">주문 없음</option></select></label>
      <label>태그<input value={value("tag", "")} onChange={(event) => updateParams({ tag: event.target.value })} placeholder="태그" /></label>
      <label>정렬<select value={value("sort", "created_desc")} onChange={(event) => updateParams({ sort: event.target.value })}><option value="created_desc">최근 가입</option><option value="last_order">최근 주문</option><option value="spent_desc">구매금액</option><option value="orders_desc">주문 수</option><option value="last_login">최근 로그인</option><option value="name">이름</option></select></label>
      <label>페이지<select value={String(pagination.pageSize)} onChange={(event) => updateParams({ pageSize: event.target.value })}><option value="20">20명</option><option value="50">50명</option><option value="100">100명</option></select></label>
    </div></form>
    <section className="admin-customer-summary" aria-label="고객 운영 요약">{[["오늘 가입", summary.todayJoined], ["이번 주 가입", summary.weekJoined], ["VIP", summary.vip], ["주의고객", summary.caution], ["휴면회원", summary.dormant], ["최근 문의", summary.recentCs], ["오늘 CS", summary.todayCs]].map(([label, count]) => <article key={String(label)}><span>{label}</span><strong>{loadState === "error" ? "-" : `${count}명`}</strong></article>)}</section>
    <p className={`admin-note ${loadState === "error" ? "error" : ""}`} role="status">{message}{loadState === "error" && <button type="button" onClick={() => void load()}>다시 시도</button>}</p>
    <section className="admin-panel admin-customers-panel"><div><h2>고객 목록</h2><span className="admin-message">총 {loadState === "error" ? "-" : pagination.total}명 · {start}~{end} 표시 · {pagination.pageSize}명 보기</span></div><div className="table-wrap"><table className="admin-customers-table"><thead><tr><th>고객</th><th>연락처</th><th>등급·상태</th><th>최근 주문</th><th>주문·구매</th><th>최근 로그인</th><th>태그</th></tr></thead><tbody>{customers.map((customer) => <tr key={customer.id} tabIndex={0} onDoubleClick={() => void loadDetail(customer.id)} onKeyDown={(event) => { if (event.key === "Enter") void loadDetail(customer.id); }}><td><button onClick={() => void loadDetail(customer.id)}>{customer.name}</button><small>{customer.id}</small></td><td><a href={`tel:${customer.phone}`}>{customer.phone || "전화번호 없음"}</a><small>{customer.email || "이메일 없음"}</small></td><td><span className={`customer-grade ${customer.grade}`}>{customerGradeLabels[customer.grade]}</span><small>{customer.status === "active" ? "정상" : "이용 제한"}</small></td><td>{customer.stats.lastOrderAt ? new Date(customer.stats.lastOrderAt).toLocaleDateString("ko-KR") : "주문 없음"}</td><td><strong>{customer.stats.orderCount}건</strong><small>{formatPrice(customer.stats.totalSpent)}</small></td><td>{customer.lastLoginAt ? new Date(customer.lastLoginAt).toLocaleDateString("ko-KR") : "기록 없음"}</td><td><div className="customer-tags">{customer.tags.map((tag) => <em key={tag}>{tag}</em>)}{!customer.tags.length && <small>없음</small>}</div></td></tr>)}{loadState === "ready" && !customers.length && <tr><td colSpan={7} className="admin-customer-empty">조건에 맞는 고객이 없습니다.</td></tr>}{loadState !== "ready" && <tr><td colSpan={7} className="admin-customer-empty">{message}</td></tr>}</tbody></table></div><nav className="admin-pagination"><small>총 {loadState === "error" ? "-" : pagination.total}명 · {start}~{end}</small><button disabled={pagination.page <= 1} onClick={() => updateParams({ page: String(pagination.page - 1) })}>이전</button><span>{pagination.page} / {pagination.pageCount}</span><button disabled={pagination.page >= pagination.pageCount} onClick={() => updateParams({ page: String(pagination.page + 1) })}>다음</button></nav></section>
    {selectedId && <CustomerDrawer id={selectedId} detail={detail} onClose={() => { setSelectedId(null); setDetail(null); }} onSaved={async () => { await loadDetail(selectedId); await load(); }} />}
  </>;
}

function CustomerDrawer({ id, detail, onClose, onSaved }: { id: string; detail: Detail | null; onClose: () => void; onSaved: () => Promise<void> }) {
  const [tags, setTags] = useState(""); const [note, setNote] = useState(""); const [channel, setChannel] = useState("전화 문의"); const [cs, setCs] = useState(""); const [message, setMessage] = useState("");
  const [saving, setSaving] = useState(false); const [feedback, setFeedback] = useState<{ tone: "success" | "danger"; text: string } | null>(null);
  useEffect(() => { if (detail) { setTags(detail.customer.tags.join(", ")); const latest = detail.logs.find((item) => item.event_type === "customer.note") as { payload?: { note?: string } } | undefined; setNote(latest?.payload?.note ?? ""); } }, [detail]);
  const save = async (body: Record<string, unknown>) => { if (saving) return; setSaving(true); try { const response = await fetch(`/api/admin/customers/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); if (!response.ok) throw new Error(); setMessage("저장되었습니다."); setFeedback({ tone: "success", text: "고객 정보를 저장했습니다." }); setCs(""); await onSaved(); } catch { setMessage("저장하지 못했습니다. 입력값은 유지됩니다."); setFeedback({ tone: "danger", text: "고객 정보를 저장하지 못했습니다." }); } finally { setSaving(false); } };
  if (!detail) return <div className="admin-customer-drawer-backdrop"><aside className="admin-customer-drawer"><p>고객 정보를 불러오는 중입니다…</p><button onClick={onClose}>닫기</button></aside></div>;
  const customer = detail.customer; const defaultAddress = detail.addresses.find((address) => address.is_default) ?? detail.addresses[0];
  return <div className="admin-customer-drawer-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><aside className="admin-customer-drawer" role="dialog" aria-modal="true" aria-label={`${customer.name} 고객 상세`}><header><div><span>CUSTOMER</span><h2>{customer.name}</h2><p>{customer.email} · {customer.phone || "전화번호 없음"}</p></div><span className={`customer-grade ${customer.grade}`}>{customerGradeLabels[customer.grade]}</span><button onClick={onClose} aria-label="고객 상세 닫기">×</button></header><nav><a href={`/admin/orders?q=${encodeURIComponent(customer.email || customer.id)}`}>주문관리</a><a href={`/admin/cs?customer=${customer.id}`}>CS 조회</a><a href={`/admin/cs?customer=${customer.id}&create=true`}>CS 접수</a><a href="#customer-addresses">주소록</a><a href="/admin/reviews">리뷰</a></nav><div className="admin-customer-drawer-body">
    <section className="customer-metrics"><article><span>총 주문</span><strong>{customer.stats.orderCount}건</strong></article><article><span>총 구매</span><strong>{formatPrice(customer.stats.totalSpent)}</strong></article><article><span>평균 주문</span><strong>{formatPrice(customer.stats.averageSpent)}</strong></article><article><span>최근 30일</span><strong>{formatPrice(customer.stats.last30DaysSpent)}</strong></article><article><span>가입일</span><strong>{new Date(customer.created_at).toLocaleDateString("ko-KR")}</strong></article><article><span>최근 로그인</span><strong>{customer.lastLoginAt ? new Date(customer.lastLoginAt).toLocaleDateString("ko-KR") : "없음"}</strong></article></section>
    <section className="customer-detail-card"><h3>태그</h3><div className="customer-edit-row"><input value={tags} onChange={(event) => setTags(event.target.value)} placeholder="VIP, 도매, 주의고객" /><button disabled={saving} onClick={() => void save({ action: "tags", tags: tags.split(",").map((tag) => tag.trim()).filter(Boolean) })}>저장</button></div></section>
    <section className="customer-detail-card"><h3>관리자 고객 메모</h3><textarea value={note} onChange={(event) => setNote(event.target.value)} placeholder="고객에게 노출되지 않는 내부 메모" /><button disabled={saving} onClick={() => void save({ action: "note", note })}>메모 저장</button></section>
    <section className="customer-detail-card"><h3>CS 응대 기록</h3><div className="customer-edit-row"><select value={channel} onChange={(event) => setChannel(event.target.value)}><option>전화 문의</option><option>카카오 상담</option><option>교환 처리</option><option>환불 처리</option><option>재발송</option><option>기타</option></select><input value={cs} onChange={(event) => setCs(event.target.value)} placeholder="응대 내용을 입력하세요" /><button disabled={saving} onClick={() => void save({ action: "cs", channel, content: cs })}>기록</button></div></section>
    <section className="customer-detail-card"><h3>주문 이력</h3><div className="customer-order-list">{detail.orders.map((order) => { const shipment = Array.isArray(order.shipments) ? order.shipments[0] as Record<string, string> : undefined; const items = order.order_items as Array<Record<string, unknown>> | undefined; return <article key={String(order.id)}><a href={`/admin/orders?q=${order.order_no}`}>{String(order.order_no)}</a><span>{new Date(String(order.created_at)).toLocaleDateString("ko-KR")}</span><p>{items?.map((item) => `${item.product_name} ${item.option_name} ×${item.quantity}`).join(" · ")}</p><strong>{formatPrice(Number(order.total_amount))}</strong><em>{String(order.status)}</em>{shipment?.tracking_number && <a target="_blank" rel="noreferrer" href={buildTrackingUrl(shipment.carrier, shipment.tracking_number) ?? "#"}>배송조회</a>}</article>; })}{!detail.orders.length && <p>주문 이력이 없습니다.</p>}</div></section>
    <section className="customer-detail-card" id="customer-addresses"><h3>배송지 {detail.addresses.length}개</h3>{defaultAddress ? <div className="customer-address"><strong>{String(defaultAddress.label || "기본 배송지")}</strong><span>{String(defaultAddress.recipient_name)} · {String(defaultAddress.phone)}</span><p>{String(defaultAddress.address)} {String(defaultAddress.address_detail || "")}</p></div> : <p>등록된 배송지가 없습니다.</p>}</section>
    <section className="customer-detail-card"><h3>Customer Timeline</h3><ol className="customer-timeline">{detail.timeline.map((event) => <li key={String(event.id)}><time>{new Date(String(event.created_at)).toLocaleString("ko-KR")}</time><strong>{String(event.label)}</strong><p>{String(event.summary || "")}</p></li>)}</ol></section>
    {message && <p className="customer-save-message" role="status">{message}</p>}{feedback && <AdminToast tone={feedback.tone} onClose={() => setFeedback(null)}>{feedback.text}</AdminToast>}
  </div></aside></div>;
}
