"use client";

import { useEffect, useRef, type ButtonHTMLAttributes, type InputHTMLAttributes, type ReactNode, type SelectHTMLAttributes, type TextareaHTMLAttributes } from "react";

type Tone = "neutral" | "info" | "success" | "warning" | "danger";
type ButtonVariant = "primary" | "secondary" | "outline" | "ghost" | "danger" | "success";
type ButtonSize = "sm" | "md" | "lg";

export function AdminButton({ variant = "primary", size = "md", loading = false, icon, children, disabled, className = "", ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { variant?: ButtonVariant; size?: ButtonSize; loading?: boolean; icon?: ReactNode }) {
  return <button {...props} disabled={disabled || loading} aria-busy={loading || undefined} className={`admin-ui-button ${variant} ${size} ${className}`.trim()}>{loading ? <span className="admin-ui-spinner" aria-hidden="true" /> : icon}{<span>{loading ? "처리 중" : children}</span>}</button>;
}

export function AdminIconButton({ label, ...props }: Omit<ButtonHTMLAttributes<HTMLButtonElement>, "aria-label"> & { label: string }) {
  return <button {...props} aria-label={label} title={label} className={`admin-ui-icon-button ${props.className ?? ""}`.trim()} />;
}

type FieldProps = { label?: string; helperText?: string; error?: string; required?: boolean; className?: string };
function Field({ label, helperText, error, required, className = "", children }: FieldProps & { children: ReactNode }) {
  return <label className={`admin-ui-field ${error ? "error" : ""} ${className}`.trim()}>{label && <span>{label}{required && <em aria-hidden="true"> *</em>}</span>}{children}{(error || helperText) && <small role={error ? "alert" : undefined}>{error || helperText}</small>}</label>;
}
export function AdminInput({ label, helperText, error, required, className, ...props }: InputHTMLAttributes<HTMLInputElement> & FieldProps) { return <Field {...{ label, helperText, error, required, className }}><input {...props} required={required} aria-invalid={Boolean(error)} /></Field>; }
export function AdminSelect({ label, helperText, error, required, className, children, ...props }: SelectHTMLAttributes<HTMLSelectElement> & FieldProps) { return <Field {...{ label, helperText, error, required, className }}><select {...props} required={required} aria-invalid={Boolean(error)}>{children}</select></Field>; }
export function AdminTextarea({ label, helperText, error, required, className, ...props }: TextareaHTMLAttributes<HTMLTextAreaElement> & FieldProps) { return <Field {...{ label, helperText, error, required, className }}><textarea {...props} required={required} aria-invalid={Boolean(error)} /></Field>; }
export function AdminCheckbox({ label, ...props }: InputHTMLAttributes<HTMLInputElement> & { label: ReactNode }) { return <label className="admin-ui-check"><input {...props} type="checkbox" /><span>{label}</span></label>; }
export function AdminRadio({ label, ...props }: InputHTMLAttributes<HTMLInputElement> & { label: ReactNode }) { return <label className="admin-ui-check"><input {...props} type="radio" /><span>{label}</span></label>; }

export function AdminBadge({ tone = "neutral", children }: { tone?: Tone; children: ReactNode }) { return <span className={`admin-ui-badge ${tone}`}>{children}</span>; }
const statusTone: Record<string, Tone> = { active: "success", selling: "success", paid: "success", delivered: "success", completed: "success", shipped: "info", checking: "info", preparing: "warning", pending: "warning", hidden: "neutral", inactive: "neutral", cancelled: "danger", refunded: "danger", urgent: "danger" };
export function AdminStatusBadge({ status, children }: { status: string; children: ReactNode }) { return <AdminBadge tone={statusTone[status] ?? "neutral"}>{children}</AdminBadge>; }

export function AdminCard({ title, description, action, footer, children, className = "" }: { title?: ReactNode; description?: ReactNode; action?: ReactNode; footer?: ReactNode; children: ReactNode; className?: string }) {
  return <section className={`admin-ui-card ${className}`.trim()}>{(title || description || action) && <header><div>{title && <h2>{title}</h2>}{description && <p>{description}</p>}</div>{action}</header>}<div className="admin-ui-card-body">{children}</div>{footer && <footer>{footer}</footer>}</section>;
}
export function AdminStatCard({ label, value, unit, tone = "neutral" }: { label: string; value: ReactNode; unit?: string; tone?: Tone }) { return <article className={`admin-ui-stat ${tone}`}><span>{label}</span><strong>{value}</strong>{unit && <small>{unit}</small>}</article>; }
export function AdminTable({ children, density = "standard", className = "" }: { children: ReactNode; density?: "compact" | "standard"; className?: string }) { return <table className={`admin-ui-table ${density} ${className}`.trim()}>{children}</table>; }
export function AdminTableContainer({ loading, error, empty, children }: { loading?: boolean; error?: string; empty?: { title: string; description?: string }; children: ReactNode }) { return <div className="admin-ui-table-container">{loading ? <AdminLoading /> : error ? <AdminErrorState message={error} /> : empty ? <AdminEmptyState {...empty} /> : children}</div>; }

export function AdminLoading({ label = "불러오는 중입니다." }: { label?: string }) { return <div className="admin-ui-state" role="status"><span className="admin-ui-spinner" aria-hidden="true" /><strong>{label}</strong></div>; }
export function AdminEmptyState({ title, description, action }: { title: string; description?: string; action?: ReactNode }) { return <div className="admin-ui-state empty"><strong>{title}</strong>{description && <p>{description}</p>}{action}</div>; }
export function AdminErrorState({ message, retry }: { message: string; retry?: () => void }) { return <div className="admin-ui-state error" role="alert"><strong>정보를 불러오지 못했습니다.</strong><p>{message}</p>{retry && <AdminButton variant="outline" onClick={retry}>다시 시도</AdminButton>}</div>; }
export function AdminSkeleton({ lines = 3 }: { lines?: number }) { return <div className="admin-ui-skeleton" aria-label="콘텐츠를 불러오는 중">{Array.from({ length: lines }, (_, index) => <i key={index} />)}</div>; }

export function AdminPageHeader({ eyebrow, title, description, action }: { eyebrow?: string; title: string; description?: string; action?: ReactNode }) { return <header className="admin-ui-page-header"><div>{eyebrow && <span>{eyebrow}</span>}<h1>{title}</h1>{description && <p>{description}</p>}</div>{action}</header>; }
export function AdminScreen({ name, children }: { name: string; children: ReactNode }) { return <div className="admin-ui-screen" data-admin-screen={name}>{children}</div>; }
export function AdminSectionHeader({ title, description, action }: { title: string; description?: string; action?: ReactNode }) { return <header className="admin-ui-section-header"><div><h2>{title}</h2>{description && <p>{description}</p>}</div>{action}</header>; }
export function AdminSearchBar({ children }: { children: ReactNode }) { return <div className="admin-ui-search">{children}</div>; }
export function AdminFilterPanel({ title = "검색 필터", children }: { title?: string; children: ReactNode }) { return <section className="admin-ui-filter"><strong>{title}</strong><div>{children}</div></section>; }

export function AdminPagination({ page, pageCount, total, start, end, unit, onPage }: { page: number; pageCount: number; total: number; start: number; end: number; unit: string; onPage: (page: number) => void }) { return <nav className="admin-ui-pagination" aria-label="페이지 이동"><span>{total ? `총 ${total}${unit} · ${start}–${end} 표시` : `총 0${unit}`}</span><AdminButton size="sm" variant="outline" disabled={page <= 1} onClick={() => onPage(page - 1)}>이전</AdminButton><b>{page} / {Math.max(1, pageCount)}</b><AdminButton size="sm" variant="outline" disabled={page >= pageCount} onClick={() => onPage(page + 1)}>다음</AdminButton></nav>; }
export function AdminTabs({ tabs, active, onChange }: { tabs: Array<{ id: string; label: string }>; active: string; onChange: (id: string) => void }) { return <div className="admin-ui-tabs" role="tablist">{tabs.map(tab => <button role="tab" aria-selected={active === tab.id} key={tab.id} onClick={() => onChange(tab.id)}>{tab.label}</button>)}</div>; }

function useAdminDialog(onClose: () => void) { const ref = useRef<HTMLElement>(null); useEffect(() => { const previous = document.activeElement as HTMLElement | null; const overflow = document.body.style.overflow; document.body.style.overflow = "hidden"; const root = ref.current; const focusable = () => Array.from(root?.querySelectorAll<HTMLElement>('button:not([disabled]),a[href],input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[tabindex]:not([tabindex="-1"])') ?? []); focusable()[0]?.focus(); const keydown = (event: KeyboardEvent) => { if (event.key === "Escape") onClose(); if (event.key === "Tab") { const items = focusable(); if (!items.length) return; const first = items[0]; const last = items[items.length - 1]; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); } } }; document.addEventListener("keydown", keydown); return () => { document.removeEventListener("keydown", keydown); document.body.style.overflow = overflow; previous?.focus(); }; }, [onClose]); return ref; }
export function AdminModal({ title, description, children, footer, onClose }: { title: string; description?: string; children: ReactNode; footer?: ReactNode; onClose: () => void }) { const ref = useAdminDialog(onClose); return <div className="admin-ui-overlay" role="presentation" onMouseDown={event => { if (event.currentTarget === event.target) onClose(); }}><section ref={ref} className="admin-ui-modal" role="dialog" aria-modal="true" aria-label={title}><AdminSectionHeader title={title} description={description} action={<AdminIconButton label="닫기" onClick={onClose}>×</AdminIconButton>} /><div>{children}</div>{footer && <footer>{footer}</footer>}</section></div>; }
export function AdminDrawer({ title, children, onClose }: { title: string; children: ReactNode; onClose: () => void }) { const ref = useAdminDialog(onClose); return <div className="admin-ui-overlay drawer"><aside ref={ref} className="admin-ui-drawer" role="dialog" aria-modal="true" aria-label={title}><AdminSectionHeader title={title} action={<AdminIconButton label="닫기" onClick={onClose}>×</AdminIconButton>} />{children}</aside></div>; }
export function AdminConfirmDialog({ title, description, confirmLabel = "확인", danger, onConfirm, onClose }: { title: string; description: string; confirmLabel?: string; danger?: boolean; onConfirm: () => void; onClose: () => void }) { return <AdminModal title={title} description={description} onClose={onClose} footer={<><AdminButton variant="ghost" onClick={onClose}>취소</AdminButton><AdminButton variant={danger ? "danger" : "primary"} onClick={onConfirm}>{confirmLabel}</AdminButton></>}>계속 진행하시려면 확인을 눌러주세요.</AdminModal>; }
export function AdminToast({ tone = "info", children, onClose, duration = 4500 }: { tone?: Tone; children: ReactNode; onClose?: () => void; duration?: number }) { useEffect(() => { if (!onClose || duration <= 0) return; const timer = window.setTimeout(onClose, duration); return () => window.clearTimeout(timer); }, [duration, onClose]); return <div className={`admin-ui-toast ${tone}`} role="status" aria-live="polite">{children}{onClose && <AdminIconButton label="알림 닫기" onClick={onClose}>×</AdminIconButton>}</div>; }
export function AdminTooltip({ label, children }: { label: string; children: ReactNode }) { return <span className="admin-ui-tooltip" data-tooltip={label}>{children}</span>; }
