export const csTypes = ["delivery_question", "delivery_delay", "missing_item", "wrong_delivery", "damage", "freshness", "quality", "exchange", "refund", "cancel", "reship", "other"] as const;
export const csStatuses = ["new", "checking", "waiting_customer", "waiting_supplier", "waiting_return", "waiting_refund", "waiting_reship", "completed", "closed"] as const;
export const csPriorities = ["urgent", "high", "normal", "low"] as const;
export type CsType = typeof csTypes[number]; export type CsStatus = typeof csStatuses[number]; export type CsPriority = typeof csPriorities[number];
export const csTypeLabels: Record<CsType, string> = { delivery_question: "배송 문의", delivery_delay: "배송 지연", missing_item: "상품 누락", wrong_delivery: "오배송", damage: "파손", freshness: "신선도 문제", quality: "품질 문의", exchange: "교환", refund: "환불", cancel: "취소", reship: "재배송", other: "기타" };
export const csStatusLabels: Record<CsStatus, string> = { new: "신규 접수", checking: "확인 중", waiting_customer: "고객 답변 대기", waiting_supplier: "공급처 확인 중", waiting_return: "회수 대기", waiting_refund: "환불 대기", waiting_reship: "재배송 대기", completed: "처리 완료", closed: "종료" };
export const csPriorityLabels: Record<CsPriority, string> = { urgent: "긴급", high: "높음", normal: "보통", low: "낮음" };
export type CsCase = { caseId: string; caseNo: string; userId: string; orderId: string | null; type: CsType; status: CsStatus; priority: CsPriority; assignee: string; content: string; attachments: string[]; createdAt: string; updatedAt: string; completedAt?: string | null };
export type CsEventRow = { event_type: string; payload: Record<string, unknown>; summary: string; actor?: Record<string, unknown>; created_at: string };
export function slaHours(priority: CsPriority) { return priority === "urgent" ? 2 : priority === "high" ? 8 : priority === "normal" ? 24 : 48; }
export function reconstructCases(events: CsEventRow[]) { const cases = new Map<string, CsCase>(); for (const event of [...events].sort((a, b) => a.created_at.localeCompare(b.created_at))) { const caseId = String(event.payload.caseId ?? ""); if (!caseId) continue; if (event.event_type === "cs.case_created") cases.set(caseId, event.payload.case as CsCase); else { const current = cases.get(caseId); if (current) cases.set(caseId, { ...current, ...(event.payload.changes as Partial<CsCase> ?? {}), updatedAt: event.created_at }); } } return [...cases.values()]; }
export function caseSla(csCase: CsCase) { const elapsedHours = (Date.now() - new Date(csCase.createdAt).getTime()) / 3600000; return { elapsedHours, targetHours: slaHours(csCase.priority), exceeded: !["completed", "closed"].includes(csCase.status) && elapsedHours > slaHours(csCase.priority) }; }
